# Generated by Django 3.2 on 2023-03-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20230303_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transacoes'},
        ),
    ]
